kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: plugins/docker
    pull: if-not-exists
    settings:
      dry_run: true
      repo: foo/bar
      tags:
      - latest
      - ${DRONE_BRANCH}
