kind: pipeline
type: docker
name: default

steps:
  - name: test_missing_secret
    image: alpine
    environment:
      SECRET:
        from_secret: this_secret_does_not_exist
    commands:
      - echo hello
      - echo $SECRET
      - echo goodbye
