kind: pipeline
type: docker
name: default

steps:
  - name: hello
    image: alpine
    pull: if-not-exists
    commands:
    - echo hello
    - echo world

  - name: backend
    image: golang
    commands:
    - go build
    - go test
    depends_on:
      - hello

  - name: frontend
    image: node
    commands:
    - npm install
    - npm test
    depends_on:
      - hello

  - name: notify
    image: plugins/slack
    settings:
      webhook:
        from_secret: webhook
    depends_on:
      - frontend
      - backend

trigger:
  event:
    - push
