kind: pipeline
type: docker
name: default

steps:
  - name: shoutout-alfa
    image: alpine
    pull: if-not-exists
    commands:
    - echo hey I belong to stage default

trigger:
  event:
    - push
