kind: pipeline
type: docker
name: default

steps:
  - name: hello
    image: alpine
    pull: if-not-exists
    commands:
    - echo hello
    - echo world

  - name: build
    image: plugins/docker
    settings:
      repo: registry.pixelpoint.io/hello-world
      registry: registry.pixelpoint.io
      tags: latest
      dry_run: true
      debug: true
    volumes:
    - name: temp
      path: /tmp
