kind: pipeline
type: docker
name: greeting

steps:
- name: en
  image: alpine
  commands:
  - echo hello
  - echo world

- name: es
  image: alpine
  commands:
  - echo hola
  - echo mundo

- name: fr
  image: alpine
  commands:
  - echo bonjour
  - echo monde

---
kind: pipeline
type: docker
name: test

steps:
- name: test
  image: alpine
  commands:
  - echo hello
  - echo world

node:
  foo: bar

depends_on:
- greeting
