kind: pipeline
name: build

steps:
- name: hello
  image: alpine:3.8
  commands:
  - echo hello
  
- name: world
  image: alpine:3.8
  commands:
  - echo world
  - exit 78
  
- name: bonjour
  image: alpine:3.8
  commands:
  - echo bonjour

- name: monde
  image: alpine:3.8
  commands:
  - echo monde

services:
- name: redis
  image: redis
