---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: alpine:3.8
  commands:
  - echo hello world
  - echo $USERNAME
  environment:
    USERNAME:
      from_secret: username

---
kind: secret
name: username
data: yaF5r1Sj3qu4G38Zcuj0mnR_DLQKK6PjShg3uxILVf0h8TL3QdK1j2qoSTwRJFwQvgf545ibL0Y=

...
