kind: pipeline
type: docker
name: greeting

steps:
- name: en
  image: alpine
  commands:
  - echo hello
  - echo world

- name: es
  image: alpine
  commands:
  - echo hola
  - echo mundo

- name: fr
  image: alpine
  commands:
  - echo bonjour
  - echo monde

- name: longrunning
  image: alpine
  commands:
  - |
    for i in {1..100}; do echo "$i minutes passed"; sleep 5; done
