kind: pipeline
type: docker
name: default

steps:
  - name: test1
    image: alpine
    pull: if-not-exists
    commands:
    - echo this should NOT execute
    when:
      repo: bradrydzewski/hello-world
    
  - name: test2
    image: alpine
    pull: if-not-exists
    commands:
    - echo this should execute
    when:
      repo: drone/hello-world
