greeting: &greeting
  image: alpine:3.8
  commands:
    - echo hello
    - echo world

kind: pipeline
type: docker
name: anchors

steps:
- name: hello
  <<: *greeting
  when:
    event: push
    branch: master
