kind: pipeline
name: build

steps:
- name: test
  image: alpine:3.8
  commands:
  - echo hello
  - echo world

services:
- name: redis
  image: redis

---

kind: pipeline
name: test

steps:
- name: test
  image: alpine:3.8
  commands:
  - echo hello
  - echo world
  - sleep 10

depends_on:
- build
