kind: pipeline
name: build

steps:
- name: test
  image: alpine:3.8
  commands:
  - echo hello
  - echo world

- name: build
  image: plugins/docker
  settings:
    username: foo
    password: bar
    repo: foo/bar
    tags: latest
