kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: alpine:3.8
    commands:
      - echo ${DRONE_BRANCH//\//-}

  - name: pushg
    image: plugins/docker
    settings:
      tag: ${DRONE_BRANCH//\//-}
      repo: foo/bar
      dry_run: true
