---
kind: pipeline
name: unit tests
type: docker

clone:
  disable: true

steps:
- name: clone
  image: alpine/git
  commands:
  - echo run clone tests

- name: run python tests
  image: alpine
  environment:
    FOO: BAR
  commands:
    - echo run python tests

trigger:
  branch:
    exclude:
      - master
