kind: pipeline
name: build

steps:
- name: test1
  image: alpine:3.8
  commands:
  - echo hello
  - echo world

- name: redis
  detach: true
  image: redis

- name: test2
  image: alpine:3.8
  commands:
  - echo hello
  - echo world
