kind: pipeline
name: build

steps:
- name: hello
  image: alpine:3.8
  commands:
  - echo hello
  
- name: world
  image: alpine:3.8
  commands:
  - echo world
  - exit 78
  
- name: goodbye
  image: alpine:3.8
  commands:
  - echo goodbye

services:
- name: redis
  image: redis
