kind: pipeline
name: build

steps:
- name: test
  image: alpine:3.8
  commands:
  - echo hello
  - echo world
  - exit 1

- name: dump
  image: alpine:3.8
  commands:
  - env
  when:
    status: [ failure ]

services:
- name: redis
  image: bradrydzewski/private
