kind: pipeline
name: default

steps:
- name: tests
  image: alpine:3.8
  commands:
    - echo "hello world"

services:
- name: microservice1
  image: redis
  pull: if-not-exists
  environment:
    RUN_MVN: "true"
    BRANCH: master

- name: microservice2
  image: redis
  pull: if-not-exists
  environment:
    RUN_MVN: "true"
    BRANCH: master

