kind: pipeline
type: docker
name: default

steps:
  - name: en
    image: alpine
    commands:
    - echo hello
    - echo world
    
  - name: fr
    image: alpine
    commands:
    - echo bounjour
    - echo monde
    when:
      ref:
        include:
        - refs/heads/feature-*
        exclude:
        - refs/heads/**
